// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	transitionsJwt "github.com/kueti
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/pkg/defines"
	"github.com/kuetix/engine/pkg/workflow"
)

func init() {
	di.Boot()
	di.DependencyInjection["jwt"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"jwt"+"/"+"token", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "token", Impl: transitionsJwt.NewJwtTransitions()}
		})
	}
}
