// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	"github.com/kuetix/engine/boot"
	"github.com/kuetix/engine/pkg/domain/interfaces"
)

func init() {
	boot.AddMetaFunctionCache(map[string]map[string]map[string]interfaces.FunctionMetadata{
		"jwt": {
			"token": {
				"GenerateToken": {
					Name:        "GenerateToken",
					NumIn:       2,
					NumOut:      1,
					ArgTypes:    []string{"string", "string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"jwtIssuer", "encryptedId"},
					ReturnNames: []string{"r"},
				},
			},
		},
	})
}
